name: CalledWorkflow
on:
  pull_request: 
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    env:
      branch_name: ${{ github.event.pull_request.head.ref }}${{ github.event.ref }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "github.event.ref is: ${{ github.event.ref }}"
        echo "github.event.pull_request.head_ref is: ${{ github.event.pull_request.head.ref }}"
        echo "Event is: ${{ github.event.ref_type }}"
        echo "env variable is: ${{ env.branch_name }}"
