name: CalledWorkflow
on:
  pull_request: 
    types:
      - closed
    branches:
      - feature/**

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Value of github.event.ref is: ${{ github.event.ref }}"
