name: CalledWorkflow
on:
  pull_request: 
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    env:
      branch_name: $GITHUB_HEAD_REF${{ github.event.ref }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Branch name is: $GITHUB_HEAD_REF${{ github.event.ref }}"
        echo "env variable is: ${{ env.branch_name }}"
