name: "Delete Event Trigger Workflow Pipeline"
on:
  delete
jobs:
  Job1:
    if: ${{ startsWith(github.event.ref, 'feature/') }}
    runs-on: ubuntu-latest
    env:
      branch_name: ${{ github.event.ref }}${{ github.event.pull_request.head.ref }}
    steps:
      - name: "Step1"
        run: |
          echo "This job is triggered when a feature ${{ github.event.ref_type }}: ${{ github.event.ref }} has been deleted"
          echo "github.event.ref is: ${{ github.event.ref }}"
          echo "github.event.pull_request.head_ref is: ${{ github.event.pull_request.head.ref }}"
          echo "Event is: ${{ github.event.ref_type }}"
          echo "Env variable is: ${{ env.branch_name }}"
          branch_name="${{ env.branch_name }}"
          echo $branch_name
          deletion_branch=$(echo $branch_name | cut -d '/' -f 2)
          echo "Deletion Branch is: $deletion_branch"
