name: "Delete Event Trigger Workflow Pipeline"
on:
  delete
jobs:
  Job1:
    if: ${{ startsWith(github.event.ref, 'feature/') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: |
          echo "This job is triggered when a feature ${{ github.event.ref_type }}: ${{ github.event.ref }} has been deleted"
          echo "Value of GITHUB_HEAD_REF is: $GITHUB_HEAD_REF"
