name: Cleanup pipeline on branch deletion
on:
  delete:

jobs:
  Delete-Sonar-Project:
    if: ${{ startsWith(github.event.ref, 'feature/') || startsWith(github.event.ref, 'fix/') || startsWith(github.event.ref, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Print Message"
        run: |
          echo "Branch Deleted: ${{ github.event.ref }}"
