name: "Delete Event Trigger Workflow Pipeline"
on:
  delete
jobs:
  Job1:
    if: ${{ startsWith(github.event.ref, 'feature/') }}
    runs-on: ubuntu-latest
    env:
      branch_name: $GITHUB_HEAD_REF${{ github.ref }}
    steps:
      - name: "Step1"
        run: |
          echo "This job is triggered when a feature ${{ github.event.ref_type }}: ${{ github.event.ref }} has been deleted"
          echo "Branch name is: $GITHUB_HEAD_REF${{ github.ref }}"
          echo "Env variable is: ${{ env.branch_name }}"
