name: "Delete Event Trigger Workflow Pipeline"
on:
  delete
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: |
          echo "This job is triggered when ${{ github.event.ref_type }} ${{ github.event.ref }} has been deleted"
