name: Example Workflow

on: push

env:
  SKIP_QGS: "QG1"

jobs:
  job1:
    runs-on: windows-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=QG2" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: |
          echo "$OUTPUT1"
          echo "are we running any quality gates: ${{ !(contains(env.OUTPUT1, 'QG2')) }}"