name: Job2 Pipeline
on:
  merge_group:
  pull_request:
    branches:
      - feature/test2
    types: [opened, reopened, synchronize]
jobs:
  CI-Job:
    runs-on: ubuntu-latest
    steps:    
      - name: "Step1"
        run: |
          echo "Step 1"