name: Testing Workflow
on: push
env:
  # Introducing quality gates for security scans & tests
  # QG1 is ----
  # QG2 is ----
  # QG3 is ----

  SKIP_QGS: "QG1 QG3" #Add <space> separated Quality Gates or ALL to skip one or more quality gates
  FORCE_RUN: false    # Variable to forcefull run all the quality gates
jobs:
  Job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step1.outputs.branchName }}
    steps:
      - id: step1
        run: |
          echo "test=${{ env.SKIP_QGS }}" >> "$GITHUB_OUTPUT"

          if [ '${{ ( startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release/*') ) }}' == 'true' ]; then
            echo "branchName=true" >> "$GITHUB_OUTPUT"
          fi
  
  # Job2:
  #   needs: Job1
  #   if: ${{ ( !( (contains(needs.Job1.outputs.output1, 'QG2')) || (contains(needs.Job1.outputs.output1, 'QG1')) ) || (needs.Job1.outputs.output2) ) }}
  #   uses: ./.github/workflows/CalledWF.yml

  # Job4:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Running Powershell script
  #       shell: pwsh
  #       run: |
  #         Write-Host $env:GITHUB_WORKSPACE
          