name: Testing Workflow
on:
  push:
  
jobs:
  Job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run-count: [One, Two]
      max-parallel: 1
    steps:
      - name: "This is step1"
        run: |
          echo "Inside step2"
          # echo "FORCE_RUN=false" >> $GITHUB_ENV
          
      - name: "This is step2"
        if: ${{ env.FORCE_RUN != '' }}
        run: |
          echo "Inside step2"

  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    environment:
      name: Approval-Gate
    steps:
      - run: echo "This is job2"

  Job3:
    runs-on: ubuntu-latest
    needs: Job2
    steps:
      - run: echo "This is job2"
