name: Testing Workflow
on: 
  push

env:
  SKIP_QGS: 'QG1'

jobs:
  PipelineExecution:
    runs-on: windows-latest
    steps:
    - name: 'Quality Gates'
      run: |
        if [[ contains( ${{env.SKIP_QGS}}, 'QG1') ]]
          echo "Skipping All Quality Gates"
        else
          echo "Running Quality Gates"
