name: Testing Workflow
on: push

env:
  SKIP_QGS: "QG1 QG2"

jobs:
  JobProperties:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - id: step1
      run: echo "test=${{ env.SKIP_QGS }}" >> "$GITHUB_OUTPUT"

  PrintValues:
    runs-on: windows-latest
    needs: JobProperties
    steps:
    - env:
          value1: ${{needs.JobProperties.outputs.output1}}
      run: |
        echo "$value1"
        echo "are we running any quality gates: ${{ !(contains($value1, 'QG2')) }}"
      
  PipelineExecution:
    needs: PrintValues
    if: ${{ !(contains(needs.JobProperties.outputs.output1, 'QG2')) }}
    uses: ./.github/workflows/CalledWF.yml
