name: Testing Workflow
on: push
env:
  SKIP_QGS: "QG1 QG3"
jobs:
  Job1:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=${{ env.SKIP_QGS }}" >> "$Env:GITHUB_OUTPUT"
  
  Job2:
    needs: Job1
    if: ${{ !( (contains(needs.Job1.outputs.output1, 'QG2')) ||  (contains(needs.Job1.outputs.output1, 'QG1')) ) }}
    uses: ./.github/workflows/CalledWF.yml