name: Testing Workflow
on: push
env:
  SKIP_QGS: "QG1"
jobs:
  Job1:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=QG2" >> "$GITHUB_OUTPUT"
  PrintValues:
    runs-on: windows-latest
    needs: Job1
    steps:
      - env:
          value1: ${{needs.Job1.outputs.output1}}
        run: |
          echo "$value1"
          echo "${{needs.Job1.outputs.output1}}"
          echo "are we running any quality gates: ${{ !(contains(env.value1, 'QG2')) }}"
      
  PipelineExecution:
    needs: PrintValues
    if: ${{ !(contains(needs.Job1.outputs.output1, 'QG2')) }}
    uses: ./.github/workflows/CalledWF.yml