name: Testing Workflow
on:
  push:
    branches:
      - feature/test2
  pull_request:
    types:
      - opened
    branches:
      - feature/test**
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: "This is step1"
        id: step1
        run: |
          echo "Event name is: ${{ github.event_name }}"
          echo "Branch Name is: $GITHUB_REF_NAME"
          echo "Branch name with context is: ${{ github.ref }}"
          echo "Head Branch is: $GITHUB_HEAD_REF"
