name: Testing Workflow
on: push

env:
  SKIP_QGS: 'QG1'

jobs:
  JobProperties:
    runs-on: windows-latest
    steps:
    - run: echo "Preparing Job Properties"
    outputs:
      Skipping_QGs: ${{ env.SKIP_QGS }}
      
  PipelineExecution:
    if: ${{ !contains(needs.JobProperties.outputs.Skipping_QGs, 'QG1') }}
    uses: ./.github/workflows/CalledWF.yml
