name: Testing Workflow
on:
  push:
  
jobs:
  Job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run-count: [One, Two]
      max-parallel: 1
    environment:
      name: Test
    steps:
      - run: echo "Approval Completed"
      
      - name: "This is step1"
        run: |
          echo "Inside step2"
          # echo "FORCE_RUN=false" >> $GITHUB_ENV
          
      - name: "This is step2"
        if: ${{ env.FORCE_RUN != '' }}
        run: |
          echo "Inside step2"
