name: Testing Workflow
on: workflow_dispatch

concurrency:
  group: test-pipeline
  cancel-in-progress: false

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: "This is step1"
        run: |
          echo "Start step1"
          sleep 120
          echo "End step1"
