name: Testing Workflow
on: 
  push

env:
  SKIP_QGS: 'QG1'

jobs:
  PipelineExecution:
    runs-on: windows-latest
    steps:
    - name: 'Quality Gates'
      run: |
        echo "Skipping QG1 Quality Gates"
      if: ${{ !contains(env.SKIP_QGS, 'QG1') }}
    - name: running something
      run: |
        echo "Running something"
