name: Testing Workflow
on: 
  push:
    branches:
    - master
    paths: 
    - ./.github/workflows/main.yml

env:
  SKIP_QGS: 'QG1'

jobs:
  PipelineExecution:
    uses: ./.github/workflows/CalledWF.yml
    with:
      SKIP_QG_Values: ${{ env.SKIP_QGS }}
