name: Testing Workflow
on: workflow_dispatch

concurrency:
  group: test-pipeline
  cancel-in-progress: true

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: "This is step1"
        run: |
          echo "Start step1"

      - name: "Wait statement"
        uses: actions/wait@v1
        with:
          time: '180s'

      - name: "This is step2"
        run: |
          echo "Start step2"
