name: Test Pipeline
on:
  merge_group:
  pull_request:
    branches:
      - feature/test2
    types: [closed]

jobs:
  Final-Job:
    runs-on: ubuntu-latest
    steps:    
      - name: "Step1"
        run: |
          echo "Step 1"