name: Test Workflow
on:
  create:
  delete:
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: "This is step1"
        run: |
          echo "Github event ref: ${{ github.event.ref }}"
          echo "Github ref: ${{ github.ref }}"
