name: Test Workflow
on:
  push:
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare artifact files"
        run: |
          mkdir -p dir1/dir2
          touch dir1/dir2/file.txt

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/dir1/dir2/file.txt

  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}
      
      - name: "Validate file"
        run: |
          ls -lart
