name: Test Workflow
on:
  create:
  delete:
jobs:
  Job1:
    if: ${{ contains(github.event.ref, 'feature/') || contains(github.event.ref, 'fix/') || contains(github.event.ref, 'hotifx/') }}
    runs-on: ubuntu-latest
    steps:
      - name: "This is step1"
        run: |
          echo "Github event ref: ${{ github.event.ref }}"
          echo "Github ref: ${{ github.ref }}"
