name: Test Workflow
on:
  push:

jobs:
  Job1:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: |
          echo "Step1"

  Job2:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: |
          echo "Step1"

  Job3:
    needs: [Job1, Job2]
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: |
          echo "Step1"