name: Test Workflow
on:
  push:
jobs:
  Job1:
    runs-on: ubuntu-latest
    outputs:
      json_data: ${{ steps.set_json_data.outputs.json_data }}
    steps:
      - name: "Create JSON data"
        id: set_json_data
        run: |
          json_data='[{"func":"func1"},{"func":"func2"}]'
          echo "json_data=$json_data" >> $GITHUB_OUTPUT

  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json_object: ${{ fromJson(needs.Job1.outputs.json_data) }}
    steps:
      - name: "Validate JSON data"
        run: |
          echo "object is: ${{ matrix.json_object }}"
