name: Test Pipeline
on:
  pull_request:
    branches:
      - feature/test2
    types: [closed]

jobs:
  Job3:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feature/test-') }}
    runs-on: ubuntu-latest
    steps:    
      - name: "Step1"
        run: |
          echo "Step 1"