name: "Validate Create Event Trigger"
on:
  # create:

  push:
    branches:
      - feature/**

jobs: 
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_value: ${{ steps.set_matrix.outputs.matrix_value }}
    steps:
      - name: set matrix
        id: set_matrix
        run: |
          echo "Setting matrix"
          list="["
          
          IFS=","
          for item in ${{ vars.SOLUTION_LIST }}
          do
            list=${list}"\"$item\","
          done

          list=$(echo ${list::-1})
          list=${list}]

          echo "Matrix Value is: $list"
          echo "matrix_value=$list" >> $GITHUB_OUTPUT
    
  Job1:
    # if: github.event.created
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution_name: ${{ fromJSON(needs.set-matrix.outputs.matrix_value) }}
      max-parallel: 1
    steps:
      - name: "Step 1"
        run: |
          echo "Solution Name: ${{ matrix.solution_name }}"
