name: "Validate Create Event Trigger"
on:
  push:

jobs: 
  set-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameter1: ["1","2","3","4"]
        parameter2: ["a","b"]
      max-parallel: 4
    steps:
      - name: set matrix
        run: |
          echo "This is step1"
          sleep 30s
