name: "Validate Create Event Trigger"
on:
  # create:

  push:
    branches:
      - feature/**

jobs: 
  Job1:
    # if: github.event.created
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1"
        run: |
          echo "Step 1"
          echo "Event is triggered by: ${{ github.event.actor }}"
