name: "Validate Create Event Trigger"
on:
  # create:

  push:
    branches:
      - feature/**

jobs: 
  Job1:
    # if: github.event.created
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution_name: ${{ fromJson(vars.SOLUTION_LIST) }}
      max-parallel: 1
    steps:
      - name: "Step 1"
        run: |
          echo "Solution Name: ${{ matrix.solution_name }}"
